param(
    [string]$WikiDir = "d:\xiangmu\_kb\wiki",
    [string]$OutPath = "d:\xiangmu\_kb\90-meta\index.md"
)

# index-generator.ps1
# Auto-generate _kb/90-meta/index.md from wiki/ structure
# Scans 5 type subdirectories (entities/concepts/comparisons/summaries/synthesis)
# Reads YAML frontmatter (title/tags/created/updated) from each .md file
# Output: grouped by type, sorted by title, with relative links
# ASCII-only script body; Chinese content lives in source data and output

# UTF-8 self-relaunch (same pattern as projects-collector.ps1)
if ($MyInvocation.CommandOrigin -eq 'Runspace' -or [Console]::OutputEncoding.WebName -eq 'utf-8') {
    & {
function Get-Frontmatter {
    param([string]$Path)

    $content = Get-Content -Path $Path -Raw -Encoding UTF8
    $fm = @{}
    $m = [regex]::Match($content, "^---\s*\r?\n(.+?)\r?\n---\s*\r?\n", "Singleline")
    if (-not $m.Success) { return $fm }
    $yaml = $m.Groups[1].Value
    foreach ($line in ($yaml -split "`r?`n")) {
        $km = [regex]::Match($line, "^(\w+):\s*(.*)$")
        if ($km.Success) {
            $key = $km.Groups[1].Value
            $val = $km.Groups[2].Value.Trim()
            # Strip surrounding quotes
            $val = $val -replace "^'(.*)'$", '$1'
            $val = $val -replace '^"(.*)"$', '$1'
            $fm[$key] = $val
        }
    }
    return $fm
}

$typeOrder = @("entities", "concepts", "comparisons", "summaries", "synthesis")
$typeDesc = @{
    entities    = "specific things: people / companies / products / tools"
    concepts    = "abstract ideas / patterns / mechanisms"
    comparisons = "side-by-side analysis of 2+ entities"
    summaries   = "compressed knowledge from multiple sources"
    synthesis   = "higher-order insights derived from entities + concepts"
}

$allPages = @()
$totalCount = 0

foreach ($t in $typeOrder) {
    $dir = Join-Path $WikiDir $t
    if (-not (Test-Path $dir)) { continue }
    $files = Get-ChildItem $dir -Filter *.md -ErrorAction SilentlyContinue
    foreach ($f in $files) {
        $fm = Get-Frontmatter -Path $f.FullName
        $title = if ($fm.title) { $fm.title } else { $f.BaseName }
        $tags = if ($fm.tags) { $fm.tags } else { "" }
        $created = if ($fm.created) { $fm.created } else { "" }
        $updated = if ($fm.updated) { $fm.updated } else { "" }
        $allPages += [PSCustomObject]@{
            type     = $t
            fileName = $f.BaseName
            title    = $title
            tags     = $tags
            created  = $created
            updated  = $updated
            relPath  = "../wiki/$t/$($f.Name)"
        }
        $totalCount++
    }
}

# Build Markdown
$lines = New-Object System.Collections.Generic.List[string]
$today = (Get-Date).ToString("yyyy-MM-dd")
$timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")

$lines.Add("---")
$lines.Add("type: index")
$lines.Add("title: knowledge base index")
$lines.Add("source: 'auto-generated by _kb/90-meta/index-generator.ps1'")
$lines.Add("created: 2026-06-19")
$lines.Add("updated: $today")
$lines.Add("confidence: stated")
$lines.Add("status: mature")
$lines.Add("tags: [index, meta]")
$lines.Add("---")
$lines.Add("")
$lines.Add("# knowledge base index")
$lines.Add("")
$lines.Add("> Auto-generated by d:\xiangmu\_kb\90-meta\index-generator.ps1")
$lines.Add("> Generated: $timestamp")
$lines.Add("> Total pages: $totalCount (across 5 type subdirectories)")
$lines.Add("> Three-layer architecture: raw / wiki (OKF 5 type) / 90-meta")
$lines.Add("> flywheel compatibility: wiki/ has fixed 5 type subdirs, subdir name = type")
$lines.Add("")
$lines.Add("## directory navigation")
$lines.Add("")
$lines.Add("- [raw/](../raw/) - human-curated sources (raw materials, notes, screenshots)")
$lines.Add("- [wiki/](../wiki/) - LLM-compiled artifacts (OKF format, grouped by type)")
$lines.Add("- [90-meta/](.) - vault meta (index / templates / obsidian config / MOC)")
$lines.Add("")
$lines.Add("## wiki pages ($totalCount total, grouped by type)")
$lines.Add("")

foreach ($t in $typeOrder) {
    $pages = $allPages | Where-Object { $_.type -eq $t } | Sort-Object -Property title
    if ($pages.Count -eq 0) { continue }
    $desc = $typeDesc[$t]
    $lines.Add("### $t/ ($($pages.Count) - $desc)")
    $lines.Add("")
    $lines.Add("| Title | File | Tags | Updated |")
    $lines.Add("|-------|------|------|---------|")
    foreach ($p in $pages) {
        $tagShort = $p.tags
        if ($tagShort.Length -gt 40) { $tagShort = $tagShort.Substring(0, 40) + "..." }
        # Escape pipe chars in fields
        $titleSafe = $p.title -replace '\|', '\|'
        $tagSafe = $tagShort -replace '\|', '\|'
        $lines.Add("| [$($p.title)]($($p.relPath)) | $($p.fileName).md | $tagSafe | $($p.updated) |")
    }
    $lines.Add("")
}

$lines.Add("## type distribution")
$lines.Add("")
$lines.Add("| Type | Count | Description |")
$lines.Add("|------|-------|-------------|")
foreach ($t in $typeOrder) {
    $c = ($allPages | Where-Object { $_.type -eq $t }).Count
    if ($c -eq 0) { continue }
    $lines.Add("| $t | $c | $($typeDesc[$t]) |")
}
$lines.Add("| **total** | **$totalCount** | |")
$lines.Add("")
$lines.Add("## update rules")
$lines.Add("")
$lines.Add("- This index is **auto-generated**; do not edit by hand")
$lines.Add("- Refresh: run `index-generator.ps1` after adding/removing wiki pages")
$lines.Add("- Recommended: add to daily maintenance (kb-daily.ps1) after kb_lint")
$lines.Add("- Single source of truth for wiki structure: this index + projects-registry.json")

$utf8Bom = New-Object System.Text.UTF8Encoding $True
[System.IO.File]::WriteAllLines($OutPath, $lines, $utf8Bom)

Write-Host "=== Index Generator ==="
Write-Host ("Wiki:  {0}" -f $WikiDir)
Write-Host ("Out:   {0}" -f $OutPath)
Write-Host ("Total: {0} pages" -f $totalCount)
foreach ($t in $typeOrder) {
    $c = ($allPages | Where-Object { $_.type -eq $t }).Count
    if ($c -gt 0) { Write-Host ("  {0,-15} {1}" -f $t, $c) }
}
Write-Host "=== Done ==="
    }
    return
}

# ANSI mode: re-launch as UTF-8
$utf8 = New-Object System.Text.UTF8Encoding $True
$content = [System.IO.File]::ReadAllText($PSCommandPath, $utf8)
$tempPath = [System.IO.Path]::GetTempFileName() + '.ps1'
[System.IO.File]::WriteAllText($tempPath, $content, $utf8)
$argList = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $tempPath)
if ($WikiDir -ne 'd:\xiangmu\_kb\wiki') { $argList += '-WikiDir'; $argList += $WikiDir }
if ($OutPath -ne 'd:\xiangmu\_kb\90-meta\index.md') { $argList += '-OutPath'; $argList += $OutPath }
& powershell.exe @argList
Remove-Item $tempPath -Force
