param(
    [string]$WikiDir = "d:\xiangmu\_kb\wiki",
    [string]$OutDir = "d:\xiangmu\_kb\90-meta",
    [int]$MinPagesPerMoc = 3,
    [switch]$DryRun
)

# moc-generator.ps1 - Auto-generate Map of Content pages by tag
# P2-8: Scan wiki/ pages, group by frontmatter tags, generate MOC pages
# Output: _kb/90-meta/moc-auto-<tag>.md (one per tag with >= MinPagesPerMoc pages)

if ($MyInvocation.CommandOrigin -eq 'Runspace' -or [Console]::OutputEncoding.WebName -eq 'utf-8') {
    & {

$ErrorActionPreference = "Continue"

# === Step 1: Scan all wiki pages ===
Write-Host "=== MOC Generator ===" -ForegroundColor Cyan
Write-Host "Scanning: $WikiDir"

$pages = @()
$typeDirs = @("entities", "concepts", "comparisons", "summaries", "synthesis")

foreach ($typeDir in $typeDirs) {
    $fullTypePath = Join-Path $WikiDir $typeDir
    if (-not (Test-Path $fullTypePath)) { continue }

    $mdFiles = Get-ChildItem $fullTypePath -Filter *.md -ErrorAction SilentlyContinue
    foreach ($mdFile in $mdFiles) {
        $content = [System.IO.File]::ReadAllText($mdFile.FullName, [System.Text.UTF8Encoding]::new($true))
        if (-not $content) { continue }

        # Parse frontmatter
        $page = @{
            File = $mdFile.FullName
            Name = $mdFile.BaseName
            Type = $typeDir
            Title = $mdFile.BaseName
            Tags = @()
            Created = ""
            Updated = ""
            RelativePath = ""
        }

        # Extract relative path from wiki/
        $relativePath = $mdFile.FullName -replace [regex]::Escape("d:\xiangmu\_kb\"), ""
        $relativePath = $relativePath -replace "\\", "/"
        $page.RelativePath = $relativePath

        # Parse YAML frontmatter
        if ($content -match '(?s)^---\r?\n(.*?)\r?\n---') {
            $frontmatter = $Matches[1]

            # Extract title
            if ($frontmatter -match '(?m)^title:\s*(.+)$') {
                $page.Title = $Matches[1].Trim().Trim('"').Trim("'")
            }

            # Extract tags (inline array: [a, b, c] or block: - a\n- b)
            if ($frontmatter -match '(?m)^tags:\s*\[(.+)\]$') {
                $tagStr = $Matches[1]
                $page.Tags = $tagStr -split ',' | ForEach-Object { $_.Trim().Trim('"').Trim("'").Trim() } | Where-Object { $_ }
            } elseif ($frontmatter -match '(?ms)^tags:\s*\r?\n((?:\s*-\s+.+\r?\n?)+)') {
                $tagBlock = $Matches[1]
                $page.Tags = [regex]::Matches($tagBlock, '(?m)^\s*-\s+(.+)$') | ForEach-Object { $_.Groups[1].Value.Trim().Trim('"').Trim("'").Trim() }
            }

            # Extract created/updated
            if ($frontmatter -match '(?m)^created:\s*(\d{4}-\d{2}-\d{2})') {
                $page.Created = $Matches[1]
            }
            if ($frontmatter -match '(?m)^updated:\s*(\d{4}-\d{2}-\d{2})') {
                $page.Updated = $Matches[1]
            }
        }

        $pages += [PSCustomObject]$page
    }
}

Write-Host "Found $($pages.Count) pages across $($typeDirs.Count) type directories"

# === Step 2: Group by tag ===
$tagMap = @{}
foreach ($page in $pages) {
    foreach ($tag in $page.Tags) {
        if (-not $tagMap.ContainsKey($tag)) {
            $tagMap[$tag] = @()
        }
        $tagMap[$tag] += $page
    }
}

Write-Host "Found $($tagMap.Count) unique tags"

# Filter tags with >= MinPagesPerMoc pages
$mocCandidates = $tagMap.GetEnumerator() | Where-Object { $_.Value.Count -ge $MinPagesPerMoc } | Sort-Object Name
Write-Host "MOC candidates (>= $MinPagesPerMoc pages): $($mocCandidates.Count)"

# === Step 3: Generate MOC pages ===
$generated = 0
$skipped = 0

foreach ($entry in $mocCandidates) {
    $tag = $entry.Name
    $tagPages = $entry.Value | Sort-Object Type, Title

    # Sanitize tag for filename
    $safeTag = $tag -replace '[^\w\-]', '-'
    $outFile = Join-Path $OutDir "moc-auto-$safeTag.md"

    # Build MOC content
    $fence = [string][char]96 + [string][char]96 + [string][char]96
    $lines = @()
    $lines += "---"
    $lines += "type: index"
    $lines += "title: MOC - $tag"
    $lines += "source: auto-generated by moc-generator.ps1"
    $lines += "created: $(Get-Date -Format 'yyyy-MM-dd')"
    $lines += "updated: $(Get-Date -Format 'yyyy-MM-dd')"
    $lines += "confidence: stated"
    $lines += "status: mature"
    $lines += "tags: [moc, auto-generated, $tag]"
    $lines += "---"
    $lines += ""
    $lines += "# MOC - $tag"
    $lines += ""
    $lines += "> Auto-generated Map of Content for tag '" + $tag + "'."
    $lines += "> Pages: $($tagPages.Count) | Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    $lines += ""
    $lines += "## Pages by Type"
    $lines += ""

    # Group by type
    $byType = $tagPages | Group-Object Type | Sort-Object Name
    foreach ($typeGroup in $byType) {
        $lines += "### $($typeGroup.Name) ($($typeGroup.Count))"
        $lines += ""
        $lines += "| Page | Updated |"
        $lines += "|------|---------|"
        foreach ($p in $typeGroup.Group) {
            $linkPath = $p.RelativePath
            $lines += "| [$($p.Title)](../$linkPath) | $($p.Updated) |"
        }
        $lines += ""
    }

    $lines += "## Related Tags"
    $lines += ""
    # Find co-occurring tags
    $relatedTags = @{}
    foreach ($p in $tagPages) {
        foreach ($t in $p.Tags) {
            if ($t -ne $tag) {
                if (-not $relatedTags.ContainsKey($t)) { $relatedTags[$t] = 0 }
                $relatedTags[$t]++
            }
        }
    }
    $topRelated = $relatedTags.GetEnumerator() | Sort-Object Value -Descending | Select-Object -First 10
    $bt = [string][char]96
    if ($topRelated) {
        foreach ($rt in $topRelated) {
            $lines += "- " + $bt + $rt.Name + $bt + " ($($rt.Value) pages)"
        }
    } else {
        $lines += "_(none)_"
    }
    $lines += ""
    $lines += "---"
    $lines += ""
    $lines += "_This MOC was auto-generated. To regenerate, run: " + $bt + "moc-generator.ps1" + $bt + "_"

    $content = $lines -join "`r`n"

    if ($DryRun) {
        Write-Host "  [dry-run] Would generate: moc-auto-$safeTag.md ($($tagPages.Count) pages)" -ForegroundColor Yellow
        $skipped++
    } else {
        [System.IO.File]::WriteAllText($outFile, $content, [System.Text.UTF8Encoding]::new($true))
        Write-Host "  Generated: moc-auto-$safeTag.md ($($tagPages.Count) pages)" -ForegroundColor Green
        $generated++
    }
}

# === Summary ===
Write-Host ""
Write-Host "=== Summary ===" -ForegroundColor Cyan
Write-Host "Total pages scanned: $($pages.Count)"
Write-Host "Total tags found: $($tagMap.Count)"
Write-Host "MOC candidates (>= $MinPagesPerMoc): $($mocCandidates.Count)"
Write-Host "MOCs generated: $generated"
Write-Host "MOCs skipped (dry-run): $skipped"
Write-Host "Output dir: $OutDir"

    }
    return
}

# ANSI mode: re-launch as UTF-8
$utf8 = New-Object System.Text.UTF8Encoding $True
$content = [System.IO.File]::ReadAllText($PSCommandPath, $utf8)
$tempPath = [System.IO.Path]::GetTempFileName() + '.ps1'
[System.IO.File]::WriteAllText($tempPath, $content, $utf8)
$argList = @('-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $tempPath)
if ($WikiDir -ne 'd:\xiangmu\_kb\wiki') { $argList += '-WikiDir'; $argList += $WikiDir }
if ($OutDir -ne 'd:\xiangmu\_kb\90-meta') { $argList += '-OutDir'; $argList += $OutDir }
if ($MinPagesPerMoc -ne 3) { $argList += '-MinPagesPerMoc'; $argList += $MinPagesPerMoc }
if ($DryRun) { $argList += '-DryRun' }
& powershell.exe @argList
$exitCode = $LASTEXITCODE
Remove-Item $tempPath -Force
exit $exitCode
